BEGIN TRANSACTION;
CREATE TABLE "activity_logs_activitylog" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "action" text NOT NULL, "module" varchar(100) NOT NULL, "created_at" datetime NOT NULL, "ip_address" char(39) NULL, "user_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "activity_logs_activitylog" VALUES(1,'User logged in successfully','authentication','2026-07-24 12:59:14.107083',NULL,2);
INSERT INTO "activity_logs_activitylog" VALUES(2,'User logged in successfully','authentication','2026-07-24 14:21:53.181906',NULL,3);
INSERT INTO "activity_logs_activitylog" VALUES(3,'User logged in successfully','authentication','2026-07-24 14:41:05.520585',NULL,2);
INSERT INTO "activity_logs_activitylog" VALUES(4,'User logged in successfully','authentication','2026-07-24 14:45:05.789775',NULL,2);
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO "auth_permission" VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO "auth_permission" VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO "auth_permission" VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO "auth_permission" VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO "auth_permission" VALUES(5,2,'add_permission','Can add permission');
INSERT INTO "auth_permission" VALUES(6,2,'change_permission','Can change permission');
INSERT INTO "auth_permission" VALUES(7,2,'delete_permission','Can delete permission');
INSERT INTO "auth_permission" VALUES(8,2,'view_permission','Can view permission');
INSERT INTO "auth_permission" VALUES(9,3,'add_group','Can add group');
INSERT INTO "auth_permission" VALUES(10,3,'change_group','Can change group');
INSERT INTO "auth_permission" VALUES(11,3,'delete_group','Can delete group');
INSERT INTO "auth_permission" VALUES(12,3,'view_group','Can view group');
INSERT INTO "auth_permission" VALUES(13,4,'add_contenttype','Can add content type');
INSERT INTO "auth_permission" VALUES(14,4,'change_contenttype','Can change content type');
INSERT INTO "auth_permission" VALUES(15,4,'delete_contenttype','Can delete content type');
INSERT INTO "auth_permission" VALUES(16,4,'view_contenttype','Can view content type');
INSERT INTO "auth_permission" VALUES(17,5,'add_session','Can add session');
INSERT INTO "auth_permission" VALUES(18,5,'change_session','Can change session');
INSERT INTO "auth_permission" VALUES(19,5,'delete_session','Can delete session');
INSERT INTO "auth_permission" VALUES(20,5,'view_session','Can view session');
INSERT INTO "auth_permission" VALUES(21,6,'add_role','Can add role');
INSERT INTO "auth_permission" VALUES(22,6,'change_role','Can change role');
INSERT INTO "auth_permission" VALUES(23,6,'delete_role','Can delete role');
INSERT INTO "auth_permission" VALUES(24,6,'view_role','Can view role');
INSERT INTO "auth_permission" VALUES(25,7,'add_rolepermission','Can add role permission');
INSERT INTO "auth_permission" VALUES(26,7,'change_rolepermission','Can change role permission');
INSERT INTO "auth_permission" VALUES(27,7,'delete_rolepermission','Can delete role permission');
INSERT INTO "auth_permission" VALUES(28,7,'view_rolepermission','Can view role permission');
INSERT INTO "auth_permission" VALUES(29,8,'add_permission','Can add permission');
INSERT INTO "auth_permission" VALUES(30,8,'change_permission','Can change permission');
INSERT INTO "auth_permission" VALUES(31,8,'delete_permission','Can delete permission');
INSERT INTO "auth_permission" VALUES(32,8,'view_permission','Can view permission');
INSERT INTO "auth_permission" VALUES(33,9,'add_customuser','Can add custom user');
INSERT INTO "auth_permission" VALUES(34,9,'change_customuser','Can change custom user');
INSERT INTO "auth_permission" VALUES(35,9,'delete_customuser','Can delete custom user');
INSERT INTO "auth_permission" VALUES(36,9,'view_customuser','Can view custom user');
INSERT INTO "auth_permission" VALUES(37,10,'add_userpermission','Can add user permission');
INSERT INTO "auth_permission" VALUES(38,10,'change_userpermission','Can change user permission');
INSERT INTO "auth_permission" VALUES(39,10,'delete_userpermission','Can delete user permission');
INSERT INTO "auth_permission" VALUES(40,10,'view_userpermission','Can view user permission');
INSERT INTO "auth_permission" VALUES(41,11,'add_folder','Can add folder');
INSERT INTO "auth_permission" VALUES(42,11,'change_folder','Can change folder');
INSERT INTO "auth_permission" VALUES(43,11,'delete_folder','Can delete folder');
INSERT INTO "auth_permission" VALUES(44,11,'view_folder','Can view folder');
INSERT INTO "auth_permission" VALUES(45,12,'add_folderpermission','Can add folder permission');
INSERT INTO "auth_permission" VALUES(46,12,'change_folderpermission','Can change folder permission');
INSERT INTO "auth_permission" VALUES(47,12,'delete_folderpermission','Can delete folder permission');
INSERT INTO "auth_permission" VALUES(48,12,'view_folderpermission','Can view folder permission');
INSERT INTO "auth_permission" VALUES(49,13,'add_file','Can add file');
INSERT INTO "auth_permission" VALUES(50,13,'change_file','Can change file');
INSERT INTO "auth_permission" VALUES(51,13,'delete_file','Can delete file');
INSERT INTO "auth_permission" VALUES(52,13,'view_file','Can view file');
INSERT INTO "auth_permission" VALUES(53,14,'add_fileversion','Can add file version');
INSERT INTO "auth_permission" VALUES(54,14,'change_fileversion','Can change file version');
INSERT INTO "auth_permission" VALUES(55,14,'delete_fileversion','Can delete file version');
INSERT INTO "auth_permission" VALUES(56,14,'view_fileversion','Can view file version');
INSERT INTO "auth_permission" VALUES(57,15,'add_notification','Can add notification');
INSERT INTO "auth_permission" VALUES(58,15,'change_notification','Can change notification');
INSERT INTO "auth_permission" VALUES(59,15,'delete_notification','Can delete notification');
INSERT INTO "auth_permission" VALUES(60,15,'view_notification','Can view notification');
INSERT INTO "auth_permission" VALUES(61,16,'add_activitylog','Can add activity log');
INSERT INTO "auth_permission" VALUES(62,16,'change_activitylog','Can change activity log');
INSERT INTO "auth_permission" VALUES(63,16,'delete_activitylog','Can delete activity log');
INSERT INTO "auth_permission" VALUES(64,16,'view_activitylog','Can view activity log');
INSERT INTO "auth_permission" VALUES(65,17,'add_mou','Can add mou');
INSERT INTO "auth_permission" VALUES(66,17,'change_mou','Can change mou');
INSERT INTO "auth_permission" VALUES(67,17,'delete_mou','Can delete mou');
INSERT INTO "auth_permission" VALUES(68,17,'view_mou','Can view mou');
INSERT INTO "auth_permission" VALUES(69,18,'add_moudocument','Can add mou document');
INSERT INTO "auth_permission" VALUES(70,18,'change_moudocument','Can change mou document');
INSERT INTO "auth_permission" VALUES(71,18,'delete_moudocument','Can delete mou document');
INSERT INTO "auth_permission" VALUES(72,18,'view_moudocument','Can view mou document');
INSERT INTO "auth_permission" VALUES(73,19,'add_mourenewal','Can add mou renewal');
INSERT INTO "auth_permission" VALUES(74,19,'change_mourenewal','Can change mou renewal');
INSERT INTO "auth_permission" VALUES(75,19,'delete_mourenewal','Can delete mou renewal');
INSERT INTO "auth_permission" VALUES(76,19,'view_mourenewal','Can view mou renewal');
INSERT INTO "auth_permission" VALUES(77,20,'add_moutemplate','Can add mou template');
INSERT INTO "auth_permission" VALUES(78,20,'change_moutemplate','Can change mou template');
INSERT INTO "auth_permission" VALUES(79,20,'delete_moutemplate','Can delete mou template');
INSERT INTO "auth_permission" VALUES(80,20,'view_moutemplate','Can view mou template');
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO "django_content_type" VALUES(1,'admin','logentry');
INSERT INTO "django_content_type" VALUES(2,'auth','permission');
INSERT INTO "django_content_type" VALUES(3,'auth','group');
INSERT INTO "django_content_type" VALUES(4,'contenttypes','contenttype');
INSERT INTO "django_content_type" VALUES(5,'sessions','session');
INSERT INTO "django_content_type" VALUES(6,'roles','role');
INSERT INTO "django_content_type" VALUES(7,'roles','rolepermission');
INSERT INTO "django_content_type" VALUES(8,'permissions','permission');
INSERT INTO "django_content_type" VALUES(9,'users','customuser');
INSERT INTO "django_content_type" VALUES(10,'users','userpermission');
INSERT INTO "django_content_type" VALUES(11,'folders','folder');
INSERT INTO "django_content_type" VALUES(12,'folders','folderpermission');
INSERT INTO "django_content_type" VALUES(13,'files','file');
INSERT INTO "django_content_type" VALUES(14,'files','fileversion');
INSERT INTO "django_content_type" VALUES(15,'notifications','notification');
INSERT INTO "django_content_type" VALUES(16,'activity_logs','activitylog');
INSERT INTO "django_content_type" VALUES(17,'mous','mou');
INSERT INTO "django_content_type" VALUES(18,'mous','moudocument');
INSERT INTO "django_content_type" VALUES(19,'mous','mourenewal');
INSERT INTO "django_content_type" VALUES(20,'mous','moutemplate');
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO "django_migrations" VALUES(1,'permissions','0001_initial','2026-07-24 12:51:16.334896');
INSERT INTO "django_migrations" VALUES(2,'roles','0001_initial','2026-07-24 12:51:16.348408');
INSERT INTO "django_migrations" VALUES(3,'contenttypes','0001_initial','2026-07-24 12:51:16.356030');
INSERT INTO "django_migrations" VALUES(4,'contenttypes','0002_remove_content_type_name','2026-07-24 12:51:16.367361');
INSERT INTO "django_migrations" VALUES(5,'auth','0001_initial','2026-07-24 12:51:16.386032');
INSERT INTO "django_migrations" VALUES(6,'auth','0002_alter_permission_name_max_length','2026-07-24 12:51:16.396265');
INSERT INTO "django_migrations" VALUES(7,'auth','0003_alter_user_email_max_length','2026-07-24 12:51:16.405603');
INSERT INTO "django_migrations" VALUES(8,'auth','0004_alter_user_username_opts','2026-07-24 12:51:16.413720');
INSERT INTO "django_migrations" VALUES(9,'auth','0005_alter_user_last_login_null','2026-07-24 12:51:16.421713');
INSERT INTO "django_migrations" VALUES(10,'auth','0006_require_contenttypes_0002','2026-07-24 12:51:16.429911');
INSERT INTO "django_migrations" VALUES(11,'auth','0007_alter_validators_add_error_messages','2026-07-24 12:51:16.442507');
INSERT INTO "django_migrations" VALUES(12,'auth','0008_alter_user_username_max_length','2026-07-24 12:51:16.452798');
INSERT INTO "django_migrations" VALUES(13,'auth','0009_alter_user_last_name_max_length','2026-07-24 12:51:16.462860');
INSERT INTO "django_migrations" VALUES(14,'auth','0010_alter_group_name_max_length','2026-07-24 12:51:16.473701');
INSERT INTO "django_migrations" VALUES(15,'auth','0011_update_proxy_permissions','2026-07-24 12:51:16.483122');
INSERT INTO "django_migrations" VALUES(16,'auth','0012_alter_user_first_name_max_length','2026-07-24 12:51:16.490608');
INSERT INTO "django_migrations" VALUES(17,'users','0001_initial','2026-07-24 12:51:16.510401');
INSERT INTO "django_migrations" VALUES(18,'activity_logs','0001_initial','2026-07-24 12:51:16.517781');
INSERT INTO "django_migrations" VALUES(19,'activity_logs','0002_initial','2026-07-24 12:51:16.534094');
INSERT INTO "django_migrations" VALUES(20,'admin','0001_initial','2026-07-24 12:51:16.548559');
INSERT INTO "django_migrations" VALUES(21,'admin','0002_logentry_remove_auto_add','2026-07-24 12:51:16.563922');
INSERT INTO "django_migrations" VALUES(22,'admin','0003_logentry_add_action_flag_choices','2026-07-24 12:51:16.573829');
INSERT INTO "django_migrations" VALUES(23,'folders','0001_initial','2026-07-24 12:51:16.583069');
INSERT INTO "django_migrations" VALUES(24,'files','0001_initial','2026-07-24 12:51:16.593058');
INSERT INTO "django_migrations" VALUES(25,'files','0002_initial','2026-07-24 12:51:16.603579');
INSERT INTO "django_migrations" VALUES(26,'files','0003_initial','2026-07-24 12:51:16.641551');
INSERT INTO "django_migrations" VALUES(27,'folders','0002_initial','2026-07-24 12:51:16.685631');
INSERT INTO "django_migrations" VALUES(28,'mous','0001_initial','2026-07-24 12:51:16.750136');
INSERT INTO "django_migrations" VALUES(29,'notifications','0001_initial','2026-07-24 12:51:16.770225');
INSERT INTO "django_migrations" VALUES(30,'notifications','0002_initial','2026-07-24 12:51:16.792336');
INSERT INTO "django_migrations" VALUES(31,'notifications','0003_notification_metadata','2026-07-24 12:51:16.811323');
INSERT INTO "django_migrations" VALUES(32,'sessions','0001_initial','2026-07-24 12:51:16.821465');
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE TABLE "files_file" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "size" bigint NOT NULL, "file_type" varchar(100) NOT NULL, "file_field" varchar(100) NOT NULL, "version_number" integer NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "folder_id" bigint NOT NULL REFERENCES "folders_folder" ("id") DEFERRABLE INITIALLY DEFERRED, "uploaded_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "files_fileversion" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "version_number" integer NOT NULL, "name" varchar(255) NOT NULL, "size" bigint NOT NULL, "file_type" varchar(100) NOT NULL, "file_field" varchar(100) NOT NULL, "created_at" datetime NOT NULL, "file_id" bigint NOT NULL REFERENCES "files_file" ("id") DEFERRABLE INITIALLY DEFERRED, "uploaded_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "folders_folder" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "parent_id" bigint NULL REFERENCES "folders_folder" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "folders_folderpermission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "is_granted" bool NOT NULL, "folder_id" bigint NOT NULL REFERENCES "folders_folder" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "mous_mou" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "mou_number" varchar(100) NOT NULL UNIQUE, "partner_organization" varchar(255) NOT NULL, "department_name" varchar(255) NULL, "effective_date" date NULL, "signed_date" date NULL, "expiry_date" date NULL, "duration_months" integer NOT NULL, "status" varchar(50) NOT NULL, "summary" text NULL, "purpose" text NULL, "objectives" text NULL, "beneficiaries" text NULL CHECK ((JSON_VALID("beneficiaries") OR "beneficiaries" IS NULL)), "opportunities" text NULL CHECK ((JSON_VALID("opportunities") OR "opportunities" IS NULL)), "custom_fields_data" text NULL CHECK ((JSON_VALID("custom_fields_data") OR "custom_fields_data" IS NULL)), "coordinator_name" varchar(255) NULL, "coordinator_designation" varchar(255) NULL, "coordinator_email" varchar(254) NULL, "coordinator_phone" varchar(50) NULL, "partner_name" varchar(255) NULL, "partner_designation" varchar(255) NULL, "partner_email" varchar(254) NULL, "partner_phone" varchar(50) NULL, "additional_notes" text NULL, "remarks" text NULL, "version_number" integer NOT NULL, "is_renewed" bool NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "department_id" bigint NULL REFERENCES "folders_folder" ("id") DEFERRABLE INITIALLY DEFERRED, "original_mou_id" bigint NULL REFERENCES "files_file" ("id") DEFERRABLE INITIALLY DEFERRED, "renewed_from_id" bigint NULL REFERENCES "mous_mou" ("id") DEFERRABLE INITIALLY DEFERRED, "signed_mou_id" bigint NULL REFERENCES "files_file" ("id") DEFERRABLE INITIALLY DEFERRED, "mou_type_id" bigint NULL REFERENCES "mous_moutemplate" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "mous_mou" VALUES(1,'ABC Technologies Internship Agreement','MOU-2026-0001','ABC Tech Corp','Engineering',NULL,'2026-01-15','2027-01-15',12,'Active','Strategic partnership agreement with ABC Tech Corp for internship opportunities.','To enhance student exposure and practical training in Engineering.',NULL,'["Students", "Faculty", "Institution"]','["Internship", "Placement", "Training"]','{}','Dr. Robert Smith',NULL,'r.smith@college.edu',NULL,'Sarah Jenkins',NULL,'contact@abctechcorp.com',NULL,NULL,NULL,1,0,'2026-07-24 12:51:38.730191','2026-07-24 12:51:38.730203',2,NULL,NULL,NULL,NULL,1);
INSERT INTO "mous_mou" VALUES(2,'IIT Bombay Joint Research Initiative','MOU-2026-0002','IIT Bombay','Medical',NULL,'2025-08-10','2027-08-10',24,'Active','Strategic partnership agreement with IIT Bombay for research opportunities.','To enhance student exposure and practical training in Medical.',NULL,'["Students", "Faculty", "Institution"]','["Internship", "Placement", "Training"]','{}','Dr. Robert Smith',NULL,'r.smith@college.edu',NULL,'Sarah Jenkins',NULL,'contact@iitbombay.com',NULL,NULL,NULL,1,0,'2026-07-24 12:51:38.737099','2026-07-24 12:51:38.737112',2,NULL,NULL,NULL,NULL,3);
INSERT INTO "mous_mou" VALUES(3,'Infosys Placement & Recruitment Drive','MOU-2026-0003','Infosys Ltd','Engineering',NULL,'2026-07-01','2027-07-01',12,'Pending Verification','Strategic partnership agreement with Infosys Ltd for placement opportunities.','To enhance student exposure and practical training in Engineering.',NULL,'["Students", "Faculty", "Institution"]','["Internship", "Placement", "Training"]','{}','Dr. Robert Smith',NULL,'r.smith@college.edu',NULL,'Sarah Jenkins',NULL,'contact@infosysltd.com',NULL,NULL,NULL,1,0,'2026-07-24 12:51:38.744845','2026-07-24 12:51:38.744863',2,NULL,NULL,NULL,NULL,2);
INSERT INTO "mous_mou" VALUES(4,'TATA Motors Industrial Training','MOU-2026-0004','TATA Motors','Commerce',NULL,'2026-02-01','2026-08-07',6,'Active','Strategic partnership agreement with TATA Motors for industry collaboration opportunities.','To enhance student exposure and practical training in Commerce.',NULL,'["Students", "Faculty", "Institution"]','["Internship", "Placement", "Training"]','{}','Dr. Robert Smith',NULL,'r.smith@college.edu',NULL,'Sarah Jenkins',NULL,'contact@tatamotors.com',NULL,NULL,NULL,1,0,'2026-07-24 12:51:38.752817','2026-07-24 12:51:38.752829',2,NULL,NULL,NULL,NULL,4);
CREATE TABLE "mous_moudocument" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "document_type" varchar(50) NOT NULL, "uploaded_at" datetime NOT NULL, "file_id" bigint NOT NULL REFERENCES "files_file" ("id") DEFERRABLE INITIALLY DEFERRED, "mou_id" bigint NOT NULL REFERENCES "mous_mou" ("id") DEFERRABLE INITIALLY DEFERRED, "uploaded_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "mous_mourenewal" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "renewed_at" datetime NOT NULL, "notes" text NULL, "original_mou_id" bigint NOT NULL REFERENCES "mous_mou" ("id") DEFERRABLE INITIALLY DEFERRED, "renewed_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "renewed_mou_id" bigint NOT NULL REFERENCES "mous_mou" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "mous_moutemplate" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL UNIQUE, "description" text NULL, "template_notes" text NULL, "fields_schema" text NOT NULL CHECK ((JSON_VALID("fields_schema") OR "fields_schema" IS NULL)), "is_active" bool NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "mous_moutemplate" VALUES(1,'Internship','MOU template for student industrial internship & practical training programs','Standard Internship template notes for coordinators.','[{"name": "duration", "label": "Duration (Months)", "type": "number"}, {"name": "students_count", "label": "Eligible Students", "type": "number"}, {"name": "stipend", "label": "Monthly Stipend", "type": "text"}]',1,'2026-07-24 12:51:38.699583','2026-07-24 12:51:38.699598',NULL);
INSERT INTO "mous_moutemplate" VALUES(2,'Placement','Template for campus recruitment and placement partnerships','Standard Placement template notes for coordinators.','[{"name": "eligible_depts", "label": "Eligible Departments", "type": "text"}, {"name": "package", "label": "Expected CTC Package", "type": "text"}, {"name": "selection_process", "label": "Selection Process", "type": "text"}]',1,'2026-07-24 12:51:38.708307','2026-07-24 12:51:38.708322',NULL);
INSERT INTO "mous_moutemplate" VALUES(3,'Research','Joint research collaboration, funding, & IP agreements','Standard Research template notes for coordinators.','[{"name": "funding", "label": "Funding Amount ($)", "type": "text"}, {"name": "research_area", "label": "Research Domain", "type": "text"}, {"name": "principal_investigator", "label": "Principal Investigator", "type": "text"}]',1,'2026-07-24 12:51:38.715168','2026-07-24 12:51:38.715183',NULL);
INSERT INTO "mous_moutemplate" VALUES(4,'Industry Collaboration','General industry-academia partnership for workshops and labs','Standard Industry Collaboration template notes for coordinators.','[{"name": "lab_setup", "label": "Co-Branded Lab Setup", "type": "text"}, {"name": "mentor", "label": "Industry Mentor", "type": "text"}]',1,'2026-07-24 12:51:38.721597','2026-07-24 12:51:38.721617',NULL);
CREATE TABLE "notifications_notification" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(200) NOT NULL, "description" text NOT NULL, "is_read" bool NOT NULL, "created_at" datetime NOT NULL, "user_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "metadata" text NULL CHECK ((JSON_VALID("metadata") OR "metadata" IS NULL)));
CREATE TABLE "permissions_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL, "codename" varchar(100) NOT NULL UNIQUE, "description" text NULL);
INSERT INTO "permissions_permission" VALUES(1,'View Folder','view_folder','Can view folders in explorer');
INSERT INTO "permissions_permission" VALUES(2,'Create Folder','create_folder','Can create folders in explorer');
INSERT INTO "permissions_permission" VALUES(3,'Rename Folder','rename_folder','Can rename folders');
INSERT INTO "permissions_permission" VALUES(4,'Delete Folder','delete_folder','Can delete folders');
INSERT INTO "permissions_permission" VALUES(5,'Create Nested Folder','create_nested_folder','Can create subfolders inside folders');
INSERT INTO "permissions_permission" VALUES(6,'Upload Files','upload_files','Can upload files');
INSERT INTO "permissions_permission" VALUES(7,'Download Files','download_files','Can download files');
INSERT INTO "permissions_permission" VALUES(8,'Delete Files','delete_files','Can delete files');
INSERT INTO "permissions_permission" VALUES(9,'Replace Files','replace_files','Can replace files (create new versions)');
INSERT INTO "permissions_permission" VALUES(10,'Preview Files','preview_files','Can preview files inline');
INSERT INTO "permissions_permission" VALUES(11,'View Notifications','view_notifications','Can view system notifications');
INSERT INTO "permissions_permission" VALUES(12,'View Dashboard','view_dashboard','Can view system dashboard stats');
INSERT INTO "permissions_permission" VALUES(13,'Manage Users','manage_users','Can view users lists and details');
INSERT INTO "permissions_permission" VALUES(14,'Create Users','create_users','Can create new users');
INSERT INTO "permissions_permission" VALUES(15,'Edit Users','edit_users','Can update user details, roles, permissions');
INSERT INTO "permissions_permission" VALUES(16,'Delete Users','delete_users','Can delete users');
CREATE TABLE "roles_role" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL UNIQUE, "description" text NULL);
INSERT INTO "roles_role" VALUES(1,'Super Admin','Super Administrator with full system control');
INSERT INTO "roles_role" VALUES(2,'Admin','Administrator who can manage files, folders, and users');
INSERT INTO "roles_role" VALUES(3,'User','Standard user who can read, preview, upload, and download files in assigned folders');
CREATE TABLE "roles_rolepermission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "permission_id" bigint NOT NULL REFERENCES "permissions_permission" ("id") DEFERRABLE INITIALLY DEFERRED, "role_id" bigint NOT NULL REFERENCES "roles_role" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "roles_rolepermission" VALUES(1,1,1);
INSERT INTO "roles_rolepermission" VALUES(2,2,1);
INSERT INTO "roles_rolepermission" VALUES(3,3,1);
INSERT INTO "roles_rolepermission" VALUES(4,4,1);
INSERT INTO "roles_rolepermission" VALUES(5,5,1);
INSERT INTO "roles_rolepermission" VALUES(6,6,1);
INSERT INTO "roles_rolepermission" VALUES(7,7,1);
INSERT INTO "roles_rolepermission" VALUES(8,8,1);
INSERT INTO "roles_rolepermission" VALUES(9,9,1);
INSERT INTO "roles_rolepermission" VALUES(10,10,1);
INSERT INTO "roles_rolepermission" VALUES(11,11,1);
INSERT INTO "roles_rolepermission" VALUES(12,12,1);
INSERT INTO "roles_rolepermission" VALUES(13,13,1);
INSERT INTO "roles_rolepermission" VALUES(14,14,1);
INSERT INTO "roles_rolepermission" VALUES(15,15,1);
INSERT INTO "roles_rolepermission" VALUES(16,16,1);
INSERT INTO "roles_rolepermission" VALUES(17,1,2);
INSERT INTO "roles_rolepermission" VALUES(18,2,2);
INSERT INTO "roles_rolepermission" VALUES(19,3,2);
INSERT INTO "roles_rolepermission" VALUES(20,4,2);
INSERT INTO "roles_rolepermission" VALUES(21,5,2);
INSERT INTO "roles_rolepermission" VALUES(22,6,2);
INSERT INTO "roles_rolepermission" VALUES(23,7,2);
INSERT INTO "roles_rolepermission" VALUES(24,8,2);
INSERT INTO "roles_rolepermission" VALUES(25,9,2);
INSERT INTO "roles_rolepermission" VALUES(26,10,2);
INSERT INTO "roles_rolepermission" VALUES(27,11,2);
INSERT INTO "roles_rolepermission" VALUES(28,12,2);
INSERT INTO "roles_rolepermission" VALUES(29,13,2);
INSERT INTO "roles_rolepermission" VALUES(30,14,2);
INSERT INTO "roles_rolepermission" VALUES(31,15,2);
INSERT INTO "roles_rolepermission" VALUES(32,16,2);
INSERT INTO "roles_rolepermission" VALUES(33,1,3);
INSERT INTO "roles_rolepermission" VALUES(34,6,3);
INSERT INTO "roles_rolepermission" VALUES(35,7,3);
INSERT INTO "roles_rolepermission" VALUES(36,10,3);
INSERT INTO "roles_rolepermission" VALUES(37,11,3);
INSERT INTO "roles_rolepermission" VALUES(38,12,3);
CREATE TABLE "users_customuser" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "name" varchar(150) NOT NULL, "phone" varchar(20) NULL, "designation" varchar(100) NULL, "department" varchar(100) NULL, "status" varchar(20) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "role_id" bigint NULL REFERENCES "roles_role" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "users_customuser" VALUES(1,'pbkdf2_sha256$1000000$Y63ECY35MbMYO2ipHFnqLZ$G454DsEld3Wcsz9pAviJnfTJkb1/Yl3pvhciPhhWBjQ=',NULL,1,'superadmin@college.edu','Super Admin',NULL,'Super Admin','MOU Dept','Active','2026-07-24 12:51:37.941827','2026-07-24 12:51:37.941856',1,1,1);
INSERT INTO "users_customuser" VALUES(2,'pbkdf2_sha256$1000000$4iFzOUz8DzMQg9heh3dZXN$W20dhHbJZ/rmLIz02x4gBaIQlzTw34AHLI44Swa+ln8=',NULL,0,'admin@college.edu','System Admin',NULL,'MOU Administrator','MOU Dept','Active','2026-07-24 12:51:38.320445','2026-07-24 12:51:38.320461',1,1,2);
INSERT INTO "users_customuser" VALUES(3,'pbkdf2_sha256$1000000$0GMnrP4qaotc6Ra9GTTYg1$vjWO9kup4a5mAe8sdb+2EQ0oU3vc6+PYmZmGJo8oh48=',NULL,0,'user@college.edu','John Doe',NULL,'MOU Analyst','MOU Dept','Active','2026-07-24 12:51:38.690355','2026-07-24 12:51:38.690371',0,1,3);
CREATE TABLE "users_customuser_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "users_customuser_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "users_userpermission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "is_granted" bool NOT NULL, "permission_id" bigint NOT NULL REFERENCES "permissions_permission" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "roles_rolepermission_role_id_permission_id_63d30676_uniq" ON "roles_rolepermission" ("role_id", "permission_id");
CREATE INDEX "roles_rolepermission_permission_id_88efada8" ON "roles_rolepermission" ("permission_id");
CREATE INDEX "roles_rolepermission_role_id_1cabcbea" ON "roles_rolepermission" ("role_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "users_customuser_role_id_75f28582" ON "users_customuser" ("role_id");
CREATE UNIQUE INDEX "users_customuser_groups_customuser_id_group_id_76b619e3_uniq" ON "users_customuser_groups" ("customuser_id", "group_id");
CREATE INDEX "users_customuser_groups_customuser_id_958147bf" ON "users_customuser_groups" ("customuser_id");
CREATE INDEX "users_customuser_groups_group_id_01390b14" ON "users_customuser_groups" ("group_id");
CREATE UNIQUE INDEX "users_customuser_user_permissions_customuser_id_permission_id_7a7debf6_uniq" ON "users_customuser_user_permissions" ("customuser_id", "permission_id");
CREATE INDEX "users_customuser_user_permissions_customuser_id_5771478b" ON "users_customuser_user_permissions" ("customuser_id");
CREATE INDEX "users_customuser_user_permissions_permission_id_baaa2f74" ON "users_customuser_user_permissions" ("permission_id");
CREATE UNIQUE INDEX "users_userpermission_user_id_permission_id_cfb58597_uniq" ON "users_userpermission" ("user_id", "permission_id");
CREATE INDEX "users_userpermission_permission_id_8e1b81b6" ON "users_userpermission" ("permission_id");
CREATE INDEX "users_userpermission_user_id_4c8a0bd4" ON "users_userpermission" ("user_id");
CREATE INDEX "activity_logs_activitylog_user_id_9ba15f3d" ON "activity_logs_activitylog" ("user_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE INDEX "files_file_folder_id_58ed1200" ON "files_file" ("folder_id");
CREATE INDEX "files_file_uploaded_by_id_b71cb484" ON "files_file" ("uploaded_by_id");
CREATE INDEX "files_fileversion_file_id_1c7a12e9" ON "files_fileversion" ("file_id");
CREATE INDEX "files_fileversion_uploaded_by_id_9fb17966" ON "files_fileversion" ("uploaded_by_id");
CREATE INDEX "folders_folder_created_by_id_bea6f36e" ON "folders_folder" ("created_by_id");
CREATE INDEX "folders_folder_parent_id_470f7767" ON "folders_folder" ("parent_id");
CREATE INDEX "folders_folderpermission_folder_id_da0b8496" ON "folders_folderpermission" ("folder_id");
CREATE INDEX "folders_folderpermission_user_id_7320c8a2" ON "folders_folderpermission" ("user_id");
CREATE UNIQUE INDEX "folders_folderpermission_user_id_folder_id_e3f18c80_uniq" ON "folders_folderpermission" ("user_id", "folder_id");
CREATE INDEX "mous_mou_created_by_id_d13be91c" ON "mous_mou" ("created_by_id");
CREATE INDEX "mous_mou_department_id_bc356653" ON "mous_mou" ("department_id");
CREATE INDEX "mous_mou_original_mou_id_d1a9de78" ON "mous_mou" ("original_mou_id");
CREATE INDEX "mous_mou_renewed_from_id_abb86a77" ON "mous_mou" ("renewed_from_id");
CREATE INDEX "mous_mou_signed_mou_id_b1a3e360" ON "mous_mou" ("signed_mou_id");
CREATE INDEX "mous_moudocument_file_id_fb13fc37" ON "mous_moudocument" ("file_id");
CREATE INDEX "mous_moudocument_mou_id_1b62d025" ON "mous_moudocument" ("mou_id");
CREATE INDEX "mous_moudocument_uploaded_by_id_b3db550d" ON "mous_moudocument" ("uploaded_by_id");
CREATE INDEX "mous_mourenewal_original_mou_id_e63937ab" ON "mous_mourenewal" ("original_mou_id");
CREATE INDEX "mous_mourenewal_renewed_by_id_248e5438" ON "mous_mourenewal" ("renewed_by_id");
CREATE INDEX "mous_mourenewal_renewed_mou_id_8191d65a" ON "mous_mourenewal" ("renewed_mou_id");
CREATE INDEX "mous_moutemplate_created_by_id_ea093f65" ON "mous_moutemplate" ("created_by_id");
CREATE INDEX "mous_mou_mou_type_id_fa9372fe" ON "mous_mou" ("mou_type_id");
CREATE INDEX "notifications_notification_user_id_b5e8c0ff" ON "notifications_notification" ("user_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('django_migrations',32);
INSERT INTO "sqlite_sequence" VALUES('django_content_type',20);
INSERT INTO "sqlite_sequence" VALUES('auth_permission',80);
INSERT INTO "sqlite_sequence" VALUES('auth_group',0);
INSERT INTO "sqlite_sequence" VALUES('django_admin_log',0);
INSERT INTO "sqlite_sequence" VALUES('files_file',0);
INSERT INTO "sqlite_sequence" VALUES('files_fileversion',0);
INSERT INTO "sqlite_sequence" VALUES('folders_folderpermission',0);
INSERT INTO "sqlite_sequence" VALUES('notifications_notification',0);
INSERT INTO "sqlite_sequence" VALUES('permissions_permission',16);
INSERT INTO "sqlite_sequence" VALUES('roles_role',3);
INSERT INTO "sqlite_sequence" VALUES('roles_rolepermission',38);
INSERT INTO "sqlite_sequence" VALUES('users_customuser',3);
INSERT INTO "sqlite_sequence" VALUES('mous_moutemplate',4);
INSERT INTO "sqlite_sequence" VALUES('mous_mou',4);
INSERT INTO "sqlite_sequence" VALUES('activity_logs_activitylog',4);
COMMIT;
