# Generated by Django 5.2.16 on 2026-07-24 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0003_initial'),
        ('folders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mou_number', models.CharField(max_length=100, unique=True)),
                ('partner_organization', models.CharField(max_length=255)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('duration_months', models.IntegerField(default=12, help_text='Duration in months')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Shared', 'Shared'), ('Signed', 'Signed'), ('Pending Verification', 'Pending Verification'), ('Active', 'Active'), ('Expired', 'Expired'), ('Renewed', 'Renewed')], default='Draft', max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('beneficiaries', models.JSONField(blank=True, default=list, null=True)),
                ('opportunities', models.JSONField(blank=True, default=list, null=True)),
                ('custom_fields_data', models.JSONField(blank=True, default=dict, null=True)),
                ('coordinator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinator_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('coordinator_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('partner_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('version_number', models.IntegerField(default=1)),
                ('is_renewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mous', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mous', to='folders.folder')),
                ('original_mou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_mous', to='files.file')),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='mous.mou')),
                ('signed_mou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_mous', to='files.file')),
            ],
        ),
        migrations.CreateModel(
            name='MOUDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('original', 'Original MOU'), ('signed', 'Signed MOU'), ('summary', 'Summary Document'), ('supporting', 'Supporting Document')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mou_documents', to='files.file')),
                ('mou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mous.mou')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MOURenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('original_mou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_history', to='mous.mou')),
                ('renewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('renewed_mou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewed_instance', to='mous.mou')),
            ],
        ),
        migrations.CreateModel(
            name='MOUTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_notes', models.TextField(blank=True, help_text='Explanation for non-technical users on why this template exists and field meanings', null=True)),
                ('fields_schema', models.JSONField(default=list, help_text='List of custom field definitions: [{name, label, type, required}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mou',
            name='mou_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mous', to='mous.moutemplate'),
        ),
    ]
