# Generated by Django 5.2.16 on 2026-07-27 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_file_size_file_google_file_id_file_mime_type_and_more'),
        ('folders', '0003_folder_google_folder_id'),
        ('mous', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_date', models.DateField()),
                ('mou_month', models.CharField(max_length=20)),
                ('mou_year', models.IntegerField()),
                ('summary', models.TextField()),
                ('purpose', models.TextField()),
                ('benefits', models.JSONField(default=list)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review_status', models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending Verification', max_length=50)),
                ('reviewer_comments', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='folders.folder')),
                ('mou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_submissions', to='mous.mou')),
                ('signed_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_submissions_signed', to='files.file')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MOUShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('View Only', 'View Only'), ('Upload Only', 'Upload Only'), ('Edit', 'Edit'), ('Full Access', 'Full Access')], default='View Only', max_length=50)),
                ('status', models.CharField(choices=[('Shared', 'Shared'), ('Viewed', 'Viewed'), ('Pending Upload', 'Pending Upload'), ('Signed MOU Uploaded', 'Signed MOU Uploaded'), ('Verified by Legal Cell', 'Verified by Legal Cell'), ('Completed', 'Completed')], default='Shared', max_length=50)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mou_shares', to='folders.folder')),
                ('mou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='mous.mou')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mou', 'department', 'user')},
            },
        ),
    ]
