# Generated by Django 5.2.16 on 2026-07-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mous', '0003_collaborationtype_departmentcategory_documenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedocument',
            name='google_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='template_pdfs/'),
        ),
    ]
