# Generated by Django 5.2.16 on 2026-07-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mous', '0004_templatedocument_google_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mou',
            name='mou_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/mous/'),
        ),
    ]
