# Generated by Django 5.2.16 on 2026-07-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mous', '0005_mou_mou_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOUCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#3B82F6', max_length=50)),
                ('icon_type', models.CharField(default='school', max_length=50)),
                ('coordinator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category_type', models.CharField(choices=[('Department', 'College Department'), ('Company', 'Company Name')], default='Department', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
