# Generated by Django 5.2.16 on 2026-07-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='google_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
