# Generated by Django 5.2.16 on 2026-07-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_folder_google_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderpermission',
            name='can_delete_own_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='can_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='can_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='can_upload',
            field=models.BooleanField(default=False),
        ),
    ]
