# Generated by Django 5.2.16 on 2026-07-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_folderpermission_can_delete_own_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folderpermission',
            old_name='can_delete_own_files',
            new_name='can_delete_own_uploads',
        ),
    ]
