# Generated by Django 5.2.16 on 2026-07-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0005_rename_can_delete_own_files_folderpermission_can_delete_own_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Signed', 'Signed'), ('Pending Review', 'Pending Review'), ('Expired', 'Expired'), ('Archived', 'Archived')], default='Active', max_length=50),
        ),
    ]
