# Generated by Django 5.2.16 on 2026-07-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0006_folder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='beneficiaries',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='duration_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='folder',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_color',
            field=models.CharField(default='Purple', max_length=50),
        ),
        migrations.AddField(
            model_name='folder',
            name='mou_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='partner_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
