# Generated by Django 5.2.16 on 2026-07-30 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0007_folder_beneficiaries_folder_department_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='beneficiaries',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='folder_color',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='mou_type',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='partner_organization',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='folder',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Signed', 'Signed'), ('Pending Review', 'Pending Review'), ('Expired', 'Expired'), ('Archived', 'Archived')], default='Active', max_length=50),
        ),
        migrations.CreateModel(
            name='FolderView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='folders.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'folder')},
            },
        ),
    ]
