# Generated by Django 5.2.16 on 2026-07-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_created_by_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table=None,
        ),
    ]
