# Generated by Django 5.2.16 on 2026-07-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_smtpsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsetting',
            name='auth_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
