# Generated by Django 5.2.16 on 2026-07-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_smtpsetting_auth_required_alter_smtpsetting_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255)),
                ('private_key_id', models.CharField(max_length=255)),
                ('private_key', models.TextField()),
                ('client_email', models.EmailField(max_length=254)),
                ('client_id', models.CharField(max_length=255)),
                ('root_folder_id', models.CharField(max_length=255)),
                ('type', models.CharField(default='service_account', max_length=100)),
                ('auth_uri', models.URLField(default='https://accounts.google.com/o/oauth2/auth')),
                ('token_uri', models.URLField(default='https://oauth2.googleapis.com/token')),
                ('auth_provider_x509_cert_url', models.URLField(default='https://www.googleapis.com/oauth2/v1/certs')),
                ('client_x509_cert_url', models.URLField(blank=True, max_length=500, null=True)),
                ('universe_domain', models.CharField(default='googleapis.com', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
