# Generated by Django 5.2.16 on 2026-07-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_googledrivesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='Blue', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_folder_color', models.CharField(default='Purple', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
                ('time_format', models.CharField(default='HH:mm:ss', max_length=50)),
                ('site_timezone', models.CharField(default='UTC', max_length=100)),
                ('enable_auto_folder_colors', models.BooleanField(default=True)),
                ('reminder_days', models.IntegerField(default=30)),
                ('expiry_warning_intervals', models.IntegerField(default=7)),
                ('auto_calculate_remaining_days', models.BooleanField(default=True)),
                ('allowed_file_types', models.CharField(default='pdf,doc,docx', max_length=255)),
                ('max_upload_size_mb', models.IntegerField(default=10)),
                ('enable_version_history', models.BooleanField(default=True)),
                ('require_summary', models.BooleanField(default=True)),
                ('require_beneficiaries', models.BooleanField(default=True)),
                ('require_signed_date', models.BooleanField(default=True)),
                ('default_sharing_permission', models.CharField(default='View Only', max_length=50)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_in_app_notifications', models.BooleanField(default=True)),
                ('enable_browser_notifications', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
