# Generated by Django 5.2.16 on 2026-07-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customstatus_systemsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomStatus',
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
