# Generated by Django 5.2.16 on 2026-07-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_customstatus_delete_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivesetting',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googledrivesetting',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googledrivesetting',
            name='connected_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='googledrivesetting',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googledrivesetting',
            name='storage_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googledrivesetting',
            name='storage_usage',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googledrivesetting',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googledrivesetting',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='googledrivesetting',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googledrivesetting',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googledrivesetting',
            name='private_key_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googledrivesetting',
            name='project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googledrivesetting',
            name='root_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
