# Generated by Django 5.2.16 on 2026-07-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_googledrivesetting_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivesetting',
            name='connection_status',
            field=models.CharField(default='Disconnected', max_length=50),
        ),
        migrations.AddField(
            model_name='googledrivesetting',
            name='default_upload_folder',
            field=models.CharField(blank=True, default='Root Repository', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googledrivesetting',
            name='last_connection_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googledrivesetting',
            name='oauth_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googledrivesetting',
            name='token_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
