# Generated by Django 5.2.16 on 2026-08-03 05:09

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_googledrivesetting_connection_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledrivesetting',
            name='access_token',
            field=users.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googledrivesetting',
            name='client_secret',
            field=users.models.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='googledrivesetting',
            name='private_key',
            field=users.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googledrivesetting',
            name='refresh_token',
            field=users.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googledrivesetting',
            name='token_data',
            field=users.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='password',
            field=users.models.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
    ]
