# Generated by Django 5.2.16 on 2026-07-27 07:53

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='google_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='web_content_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='web_view_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='google_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to=files.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to=files.models.file_version_upload_path),
        ),
    ]
