# Generated by Django 5.2.16 on 2026-07-28 10:59

import backend.middleware
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_fileownership_filepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileownership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=backend.middleware.custom_timezone_now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileownership',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_ownerships_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileownership',
            name='created_by_role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fileownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_ownerships_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileownership',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_ownerships_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='filepermission',
            unique_together={('file', 'user')},
        ),
    ]
