# Generated by Django 5.2.16 on 2026-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_delete_fileownership_filepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
