# Generated by Django 5.2.16 on 2026-08-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_file_is_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='file',
            name='encryption_key_id',
            field=models.CharField(default='Google-Drive-AES-256', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='virus_scan_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='encryption_key_id',
            field=models.CharField(default='Google-Drive-AES-256', max_length=100),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='virus_scan_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
